Данные выкачанные с https://discomap.eea.europa.eu/map/fme/AirQualityExport.htm представлены в виде отдельных файлов, соответствующих отдельным годам для каждой измерительной станции. В связи с большим количеством данных, предварительный анализ планируется провести для столиц 2 выбранных стран (Берлин и Париж).
<br>
Датасеты для выбранных стран будут формироваться следующим образом:<br>1) Данные о соответствии станций городам будут взяты из AirBase_v8_stations https://www.eea.europa.eu/data-and-maps/data/airbase-the-european-air-quality-database-8
<br>2) После составления списков станций типа "urban" соответствующих выбранным городам для каждого загрязнителя будут созданы по 2 объединенных csv-файла для Берлина и Парижа соответственно.
<br>3) Полученные датасеты будут использованы для исследовательского анализа данных.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('AirBase_v8_stations.csv', sep="\t")
pd.set_option('display.max_columns', None)
df.info()                                                    
df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8626 entries, 0 to 8625
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   station_european_code         8626 non-null   object
 1   station_local_code            8374 non-null   object
 2   country_iso_code              8626 non-null   object
 3   country_name                  8626 non-null   object
 4   station_name                  8626 non-null   object
 5   station_start_date            8626 non-null   object
 6   station_end_date              2514 non-null   object
 7   type_of_station               8623 non-null   object
 8   station_ozone_classification  3647 non-null   object
 9   station_type_of_area          8626 non-null   object
 10  station_subcat_rural_back     2785 non-null   object
 11  street_type                   2887 non-null   object
 12  station_longitude_deg         8626 non-null   float64
 13  station_latitude_deg          8626 non-null   float64
 14  station_altitude              8626 non-null   int64
 15  station_city                  6846 non-null   object
 16  lau_level1_code               3161 non-null   object
 17  lau_level2_code               4570 non-null   object
 18  lau_level2_name               6306 non-null   object
 19  EMEP_station                  8626 non-null   object
dtypes: float64(2), int64(1), object(17)
memory usage: 1.3+ MB

,station_european_code,station_local_code,country_iso_code,country_name,station_name,station_start_date,station_end_date,type_of_station,station_ozone_classification,station_type_of_area,station_subcat_rural_back,street_type,station_longitude_deg,station_latitude_deg,station_altitude,station_city,lau_level1_code,lau_level2_code,lau_level2_name,EMEP_station
8621,TR0116A,TR8110001,TR,Turkey,ZONGULDAK,2008-01-01,NaN,Background,NaN,urban,NaN,NaN,31.783611,41.450558,10,ZONGULDAK,NaN,NaN,NaN,no
8622,TR0120A,TR8110002,TR,Turkey,ZONGULDAK2-KARADENIZEREGLI,2012-01-01,NaN,Background,NaN,urban,NaN,NaN,31.433000,41.276000,0,ZONGULDAK,NaN,NaN,NaN,no
8623,XK0003A,KS0103,XK,Kosovo under UNSCR 1244/99,Drenas-Municipality,2010-04-04,NaN,Background,NaN,urban,NaN,NaN,20.896210,42.625570,569,DRENAS(GLLOGOVC),NaN,NaN,NaN,no
8624,XK0002A,KS0102,XK,Kosovo under UNSCR 1244/99,Prishtine-Build ex Rilindja,2010-06-05,NaN,Traffic,NaN,urban,NaN,NaN,21.092636,42.393471,583,Prishtine,NaN,NaN,NaN,no
8625,XK0001A,KS0101,XK,Kosovo under UNSCR 1244/99,Prishtine-HMIK,2009-09-01,NaN,Background,NaN,suburban,NaN,NaN,21.081350,42.385586,573,Prishtine,NaN,NaN,NaN,no

In [3]:
df_de = df [df['country_iso_code']=='DE']
df_fr = df [df['country_iso_code']=='FR']

In [4]:
display(df_de['station_type_of_area'].unique())
df_fr['station_type_of_area'].unique()

array(['urban', 'suburban', 'rural'], dtype=object)

array(['urban', 'suburban', 'rural', 'unknown'], dtype=object)

In [1]:
#display(df_fr['station_city'].unique())
#df_de['station_city'].unique()

Во Франции присутствуют станции с типом "unknown". Посмотрим количество станций типа urban и unknown конкретно в Париже:

In [6]:
display(len(df_fr[(df_fr['station_type_of_area']=='urban') & (df_fr['station_city'].str.contains("PARIS")==True)]))
display(len(df_fr[(df_fr['station_type_of_area']=='unknown') & (df_fr['station_city'].str.contains("PARIS")==True)]))

11

0

И заодно посмотрим количество станций типа urban в Берлине:

In [7]:
display(len(df_de[(df_de['station_type_of_area']=='urban') & (df_de['station_city'].str.contains("BERLIN")==True)]))

20

А теперь получим списки станций для Парижа и Берлина, и посмотрим сколько из них активно на данный момент (NaN в колонке 'station_end_date':

In [13]:
df_berlin = df_de[(df_de['station_type_of_area']=='urban') & (df_de['station_city'].str.contains("BERLIN")==True)]
df_paris = df_fr[(df_fr['station_type_of_area']=='urban') & (df_fr['station_city'].str.contains("PARIS")==True)]

Выберем только те станции, которые активны на данный момент:

In [15]:
df_berlin_active = df_berlin.query('station_end_date !=station_end_date')
df_berlin_active.head()

,station_european_code,station_local_code,country_iso_code,country_name,station_name,station_start_date,station_end_date,type_of_station,station_ozone_classification,station_type_of_area,station_subcat_rural_back,street_type,station_longitude_deg,station_latitude_deg,station_altitude,station_city,lau_level1_code,lau_level2_code,lau_level2_name,EMEP_station
1043,DEBE065,DEBE065,DE,Germany,B Friedrichshain-Frankfurter Allee,1993-09-01,NaN,Traffic,NaN,urban,unknown,Canyon street: L/H < 1.5,13.469931,52.514072,40,BERLIN,NaN,11000000,"Berlin, Stadt",no
1056,DEBE066,DEBE066,DE,Germany,B Karlshorst-Rheingoldstr./Königswinterstr.,1999-07-01,NaN,Background,NaN,urban,unknown,NaN,13.529503,52.485261,35,BERLIN,NaN,11000000,"Berlin, Stadt",no
1076,DEBE064,DEBE064,DE,Germany,B Neukölln-Karl-Marx-Str. 76,1993-08-01,NaN,Traffic,NaN,urban,unknown,Canyon street: L/H < 1.5,13.433967,52.481709,40,BERLIN,NaN,11000000,"Berlin, Stadt",no
1077,DEBE034,DEBE034,DE,Germany,B Neukölln-Nansenstraße,1986-03-01,NaN,Background,urban,urban,unknown,NaN,13.430844,52.489451,35,BERLIN,NaN,11000000,"Berlin, Stadt",no
1078,DEBE063,DEBE063,DE,Germany,B Neukölln-Silbersteinstr.,1996-05-01,NaN,Traffic,NaN,urban,unknown,Canyon street: L/H < 1.5,13.441654,52.467534,40,BERLIN,NaN,11000000,"Berlin, Stadt",no

In [16]:
df_paris_active = df_paris.query('station_end_date !=station_end_date')
df_paris_active.head()

,station_european_code,station_local_code,country_iso_code,country_name,station_name,station_start_date,station_end_date,type_of_station,station_ozone_classification,station_type_of_area,station_subcat_rural_back,street_type,station_longitude_deg,station_latitude_deg,station_altitude,station_city,lau_level1_code,lau_level2_code,lau_level2_name,EMEP_station
3822,FR04031,FR04031,FR,France,Av Champs Elysees,1990-01-24,NaN,Traffic,NaN,urban,NaN,NaN,2.311944,48.868889,34,PARIS 8E ARRONDISSEMENT,7599,NaN,Paris,no
3902,FR04131,FR04131,FR,France,Boulevard Haussmann,2010-02-08,NaN,Traffic,NaN,urban,NaN,NaN,2.330278,48.873333,42,PARIS 9E ARRONDISSEMENT,7599,NaN,Paris,no
4174,FR0329A,FR0329A,FR,France,Genevilliers-60 av. de Richelieu-Gennevilliers,1979-01-01,NaN,Unknown,NaN,urban,NaN,Unknown,2.295011,48.931114,30,PARIS,9286,NaN,Gennevilliers,no
4511,FR04014,FR04014,FR,France,PARIS 12eme,1991-09-07,NaN,Background,NaN,urban,NaN,NaN,2.395000,48.837222,50,PARIS 12E ARRONDISSEMENT,7599,NaN,Paris,no
4515,FR04004,FR04004,FR,France,PARIS 18eme,1986-01-21,NaN,Background,urban,urban,NaN,NaN,2.346667,48.891667,71,PARIS 18E ARRONDISSEMENT,7599,NaN,Paris,no

В названиях всех файлов указан цифровой код станции, а в нашем случае мы получили коды станции, содержащие помимо цифр также и буквы. Поэтому теперь нам необходимо найти цифровые коды станций. Ведь именно по ним мы будем выбирать данные для наших датасетов. Для этого откроем файл с актуальными метаданными.

In [20]:
df_meta = pd.read_csv('PanEuropean_metadata.csv', sep="\t")
df_meta.info()                                          
#df_meta.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66163 entries, 0 to 66162
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Countrycode               66163 non-null  object
 1   Timezone                  66163 non-null  object
 2   Namespace                 66163 non-null  object
 3   AirQualityNetwork         66163 non-null  object
 4   AirQualityStation         66163 non-null  object
 5   AirQualityStationEoICode  66163 non-null  object
 6   AirQualityStationNatCode  66133 non-null  object
 7   SamplingPoint             66163 non-null  object
 8   SamplingProces            66160 non-null  object
 9   Sample                    62077 non-null  object
 10  AirPollutantCode          66163 non-null  object
 11  ObservationDateBegin      59674 non-null  object
 12  ObservationDateEnd        16417 non-null  object
 13  Projection                66163 non-null  object
 14  Longitude                 66163 non-null  float64
 15  Latitude                  66163 non-null  float64
 16  Altitude                  66163 non-null  float64
 17  MeasurementType           63557 non-null  object
 18  AirQualityStationType     66163 non-null  object
 19  AirQualityStationArea     66163 non-null  object
 20  EquivalenceDemonstrated   60643 non-null  object
 21  MeasurementEquipment      30002 non-null  object
 22  InletHeight               66163 non-null  float64
 23  BuildingDistance          66163 non-null  float64
 24  KerbDistance              66163 non-null  float64
dtypes: float64(6), object(19)
memory usage: 12.6+ MB

К сожалению выявлена серьезная проблема со скачанными данными. Анализ файла с метаданными выявил отсутствие колонки для идентификатора 'localid" станции указанного в названии файлов csv в метаданных. При этом, при просмотре нескольких случайно выбранных файлов какой-либо четкой закономерности нумерации и присваивания localid EoI-кодам выявлено не было. Так, например, EoI-коду DERP020 соответствует localid 3541, EoI-коду DERP019 - 3546, а DEBB032 - 3626. Также, в ходе проверки кодов в колонке AirQualityStationNatCode по папке с файлами не удалось найти ни одного совпадения с соответствием страны(например код 8145, который здесь приведен для Греции, используется в названиях файлов, соответствующих Германии). 	
<br>
Для того чтобы получить такую таблицу соответствия localid и EoI-кодов, необходимо: 
1) для загрязнителя с наибольшим количеством файлов в каждом датасете создать колонку localid записав туда локальный id, извлеченный из названия файла. 
<br>2) Затем нам необходимо объединить все файлы для выбранной страны в один единый датасет. 
<br>3) И затем из полученного датасета извлечь таблицу соответствия localid и EoI-кодов для выбранной страны
<br>4) Повторить все то же самое для других стран, данные которых планируется использовать в работе

В связи с неудобством работы с датасетами очень большого размера (больше нескольких гигабайт), времязатратностью написания и исполнения кода для работы с такими датасетами, в качестве возможных альтернатив видятся два возможных решения:
<br>
1) Проверить несколько других стран и посмотреть будет ли в них такая же проблема с localid. Если получится найти страны где есть привязка localid к EoI-кодам, использовать их для дальнейшей работы.
<br>2) Пересмотреть подход к работе и выбрать страну (или страны) с небольшим количеством данных для каждого загрязнителя, для того чтобы их можно было объединить в датасеты не слишком большого размера.

In [12]:
df_meta_country = df_meta[df_meta['Countrycode']=='NO']
display(df_meta_country['AirQualityStationNatCode'].unique())

array(['812', '9', '5', '428', '325', '425', '427', '426', '404', '429',
       '765', '7', '4', '856', '20', '223', '43', '15', '345', '263',
       '244', '243', '11', '12', '303', '283', '284', '14', '444', '203',
       '364', '384', '22', '464', '625', '525', '585', '304', '705',
       '830', '806', '808', '665', '666', '504', '605', '814', '827',
       '843', '163', '847', '853', '854', '852', '818', '896', '894',
       '885', '857', '815', '924', '959', '981', '1088', '985', '1091',
       '1087', '1137', '1136', '1140', '1142', '1143', '1150', '1147',
       '1145', '1146', '1141', '1148', '1144', '1152', '1161', '1162',
       '1164', '1163', '1159', '1167', '1168', '1172', '1174', '1175',
       '1173', '1155', '1169', '1170'], dtype=object)

Здесь, для Норвегии максимальные значения 'AirQualityStationNatCode' являются четырехзначными. А в папке с загруженными файлами localid, указанные в названниях файлов, находятся в диапазоне с 28633-76736. Проверка еще нескольких случайно выбранных стран показала, что значения в данный колонке ни для одной страны не совпадают с localid в названиях файлов. Исходя из этого делаем вывод, что в таблице отсутствует информация по кодам localid. Попытка найти таблицу соответствия localid и StationEoICode на сайте eea.europa.eu и на других сайтах оказалась безуспешной. Поэтому единственным наиболее реалистичным вариантом остается выбор стран с небольшим количеством данных. <br>Для последующего исследовательского анализа данных было выбрано 2 страны: <br>1) Дания - как пример страны с относительно низкой степенью загрязненности воздуха. <br>2) Сербия - как пример страны с высокой степенью загрязненности воздуха.